# Generated by Django 4.2.7 on 2023-11-10 04:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_cart_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
    ]
